class Text:
	customer_name_text = 'Please enter the customer name'
	first_payment_day_text = 'Please enter the date the customer paid us for the first time (dd/mm/yyyy)'
	instalments_text = 'Please enter the amount of instalments'
	start_date_text = 'Please enter the tenancy start date (dd/mm/yyyy)'
	end_date_text ='Please enter the tenancy end date (dd/mm/yyyy)'
	date_of_termination_text = 'Please enter the date of mutual termination (dd/mm/yyyy)'
	fee_text = 'Please enter the Fee as per Contract'

	customer_name = 'Customer Name:'
	first_payment_day = 'Date of first payment:'
	instalments = 'Amount of instalments:'
	start_date = 'Tenancy start date:'
	end_date = 'Tenancy end date:'
	date_of_termination = 'Date of mutual termination:'
	fees = 'Fees as per contract:'
	contract_days = 'Total days as per contract:'
	cost_per_day = 'Cost for each day:'
	days_used = 'Actual days used:'
	months_used = 'Actual months used:'
	cost_used = 'Used cost:'
	admin_cost = 'Admin fee:'
	total_cost = 'The total cost (including "used cost" + "admin fee"):'
	HH_outstanding_value = 'Housing Hand owes:'
	customer_outstanding_value = 'Customer owes:'